// // import type { Metadata } from 'next';
// // import { Inter } from 'next/font/google';
// import "./globals.css";
// import { cn } from "@/lib/utils";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import MaxWidthWrapper from "@/components/MaxWidthWrapper";

// // const inter = Inter({ subsets: ['latin'] });

// // export const metadata: Metadata = {
// //     title: 'Create Next App',
// //     description: 'Generated by create next app',
// // };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <header className="fixed inset-x-0 top-0 z-10 w-full ">
//         <Navbar />
//       </header>
//       <MaxWidthWrapper>{children}</MaxWidthWrapper>
//       <Footer />
//     </html>
//   );
// }

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
      // className={cn("h-full w-full font-sans font-light antialiased")}
      >
        <header>
          <Navbar />
        </header>

        <MaxWidthWrapper>{children}</MaxWidthWrapper>
        <Footer />
      </body>
    </html>
  );
}
