// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("grainy h-full  w-full font-sans font-light antialiased")}
      >
        <header className="fixed top-0 w-full">
          <Navbar />
        </header>

        <MaxWidthWrapper>{children}</MaxWidthWrapper>
        <Footer />
      </body>
    </html>
  );
}
