import "./globals.css";
import kiki from "/public/images/kikis-broom-nuage 3.svg";
import leftImage from "/public/images/g-ellipse.svg";
import rightImage from "/public/images/Ellipse.svg";

import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Image from "next/image";

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="grid-rows-layout grid min-h-screen">
          <header>
            <Navbar />
          </header>

          <MaxWidthWrapper>{children}</MaxWidthWrapper>

          <div className="relative flex flex-col justify-center overflow-hidden align-middle">
            {/* <Image
              src={leftImage}
              alt="left"
              width={1113}
              height={855}
              className={cn(
                "right-100 absolute top-0 mb-[-60px] hidden h-full 2xl:block",
              )}
            /> */}

            <Image
              src={kiki}
              alt="kikis"
              width={1500}
              height={790}
              className={cn("z-10 mx-auto mb-[-55px]")}
            />
            {/* 
            <Image
              src={rightImage}
              alt="right"
              width={822}
              height={844}
              className={cn(
                "absolute right-0 top-0 mb-[-55px] hidden h-full 2xl:block",
              )}
            /> */}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
